global:
  nodeSelector: {}
  affinity: {}
  tolerations: {}

replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmni
  name: pacs-integration
  tag: latest


config:
  TZ: ""
  PACS_INTEGRATION_DB_HOST: ""
  PACS_INTEGRATION_DB_PORT: ""
  PACS_INTEGRATION_DB_NAME: ""
  OPENMRS_HOST: ""
  OPENMRS_PORT: ""
    
secrets:
  PACS_INTEGRATION_DB_USERNAME: ""
  PACS_INTEGRATION_DB_PASSWORD: ""
  OPENMRS_ATOMFEED_USER: ""
  OPENMRS_ATOMFEED_PASSWORD: ""


autoscaling:
  enabled: false

nodeSelector: {}
affinity: {}
tolerations: {}
