apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  DB_USERNAME: {{ .Values.secrets.DB_USERNAME | b64enc | quote }}
  DB_USERNAME: {{ .Values.secrets.PACS_INTEGRATION_DB_PASSWORD | b64enc | quote}}
  OPENMRS_ATOMFEED_USER: {{ .Values.secrets.OPENMRS_ATOMFEED_USER | b64enc | quote }}
  OPENMRS_ATOMFEED_PASSWORD: {{ .Values.secrets.OPENMRS_ATOMFEED_PASSWORD | b64enc | quote}}