name: Build and Publish OHIF
on:
  workflow_dispatch:
    inputs:
      ohif_version:
        description: 'OHIF Viewers version tag (e.g. v3.8.0)'
        required: true
        type: string

jobs:
  build-publish-docker:
    name: Build & Publish OHIF Docker Image
    runs-on: ubuntu-latest
    env:
      HELM_CHART_PATH: package/ohif/helm
    steps:
      - name: Checkout Pacs Integration Repository
        uses: actions/checkout@v6

      - name: Checkout OHIF Viewers Repository
        uses: actions/checkout@v6
        with:
          repository: OHIF/Viewers
          ref: ${{ inputs.ohif_version }}
          path: Viewers

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          context: Viewers/
          platforms: linux/amd64,linux/arm64
          file: Viewers/Dockerfile
          build-args: |
            PUBLIC_URL=/ohif/
          push: true
          tags: |
            bahmni/ohif:${{ inputs.ohif_version }}
            bahmni/ohif:latest

      - name: Helm - Update Version and Image Tag
        run: |
          yq --inplace '.image.tag = "${{ inputs.ohif_version }}"' $HELM_CHART_PATH/values.yaml
          yq --inplace '.version = "${{ inputs.ohif_version }}"' $HELM_CHART_PATH/Chart.yaml

      - name: Helm Lint
        run: helm lint $HELM_CHART_PATH

      - name: Helm Package
        run: helm package $HELM_CHART_PATH

      - name: Helm - Checkout Charts Repository
        uses: actions/checkout@v2
        with:
          repository: Bahmni/helm-charts
          ref: gh-pages
          path: helm-charts
          persist-credentials: false

      - name: Helm - Copy chart
        run: mkdir -p helm-charts/ohif/ && cp ohif-${{ inputs.ohif_version }}.tgz helm-charts/ohif/

      - name: Helm - reIndex
        working-directory: helm-charts/
        run: helm repo index --merge index.yaml --url https://bahmni.github.io/helm-charts/  .

      - name: Helm - Publish Chart
        working-directory: helm-charts/
        run: |
          git config user.name ${{ secrets.BAHMNI_USERNAME}}
          git config user.email ${{ secrets.BAHMNI_EMAIL}}
          git add .
          git commit -m "Release of ohif-${{ inputs.ohif_version }}"
          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/bahmni/helm-charts.git' gh-pages